Disallow TXT files
nf-core/differentialabundance pull request #304
Opened 2024-10-21 12:33 UTC by WackerO

Currently, the pipeline does not properly handle contrast files with the TXT extension; they are treated as comma-separated which results in an error. This behaviour is now fixed.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/differentialabundance/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/differentialabundance _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nf-test test main.nf.test -profile test,docker`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-10-21 16:40 UTC, pinin4fjords requested changes
I don't agree with this, you've just flipped the problem and created another one.

txt doesn't imply any particular extension- commas or tabs. Therefore we should just restrict the input to csv|tsv and disallow txt - not assume that txt has tabs.

2024-10-22 06:47 UTC, WackerO commented
You're right, txt doesn't imply anything, but we have treated txt as a tab-separated file format for all the other files; your `read_delim_flexible` function makes the same assumption. I do think that we should treat this uniformly and either continue the same assumption here or disallow txt files in general.

2024-10-22 11:43 UTC, pinin4fjords commented
Yes, let's disallow!

2024-10-24 09:13 UTC, pinin4fjords approved these changes

2024-10-24 10:54 UTC, merged