Add pipeline-level nf-tests and CI sharding
nf-core/differentialabundance pull request #343
Opened 2024-11-08 12:40 UTC by atrigila

Closes #61 

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/differentialabundance/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/differentialabundance _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nf-test test main.nf.test -profile test,docker`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-11-08 16:34 UTC, pinin4fjords requested changes
Amazing work, thank you. But any chance we can do it without the sharding? I've been 'discussing' with one or two people about it, and I'm not a fan. It's essentially really hard to work out what's being tested because nothing is named informatively.

I don't think we have enough components here for us to exceed the test limits and make sharding necessary anyway.

2024-11-08 17:13 UTC, nschcolnicov approved these changes
Looks great, love the new nf-test implementation, so much simple

2024-11-11 09:27 UTC, pinin4fjords commented
> Looks great, love the new nf-test implementation, so much simple. Regarding @pinin4fjords comment about sharding, I also think it is easier to understand the tests, but I'm curious to know if we use sharding to make tests run faster or to save costs. If it is the latter, isn't it better to have it, even if reading the tests is a little bit harder?

As I understand it the sharding was introduced to bypass GitHub's limits on the numbers of independent tests, not out of any consideration to costs. In any case, by time is more valuable than computer time, so I'd like to save myself squinting at inscrutable test names.

2024-11-11 09:32 UTC, pinin4fjords requested changes
Could you update the CHANGELOG please, following the conventions there (e.g. for some reason we put newer entries at the top ;-) ).

Then you'll have my tick :-)

2024-11-11 12:40 UTC, atrigila commented
@pinin4fjords done :) thank you!

2024-11-11 13:46 UTC, pinin4fjords approved these changes
Brilliant- thanks for setting this up

2024-11-11 13:47 UTC, pinin4fjords commented on CHANGELOG.md
> +- [[#343](https://github.com/nf-core/differentialabundance/pull/343)] - Add pipeline-level nf-tests ([@atrigila](https://github.com/atrigila), review by [@pinin4fjords](https://github.com/pinin4fjord
```suggestion
- [[#343](https://github.com/nf-core/differentialabundance/pull/343)] - Add pipeline-level nf-tests ([@atrigila](https://github.com/atrigila), review by [@pinin4fjords](https://github.com/pinin4fjords)) and [@nschcolnicov](https://github.com/nschcolnicov))
```
oops, just a bracket

2024-11-11 14:31 UTC, merged