Contrasts schema validation
nf-core/differentialabundance pull request #410
Opened 2024-12-20 13:08 UTC by nschcolnicov

To close https://github.com/nf-core/differentialabundance/issues/405 once the issue in the schema plugin is sorted out

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/differentialabundance/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/differentialabundance _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nf-test test main.nf.test -profile test,docker`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2025-01-09 13:25 UTC, grst commented on workflows/differentialabundance.nf
> +        ch_contrast_variables.dump(tag:"ch_contrasts_variables")
I think we should just get rid of the csv sheet right away. As we support more complex contrasts, csv won't be useful anymore and this is anyway why we decided to move towards yaml.

2025-01-13 12:23 UTC, nschcolnicov commented
Waiting on new nf-schema version 2.3.0 soon to be released

2025-01-13 12:24 UTC, nschcolnicov commented on workflows/differentialabundance.nf
> +        ch_contrast_variables.dump(tag:"ch_contrasts_variables")
I didn't want to have it from the start to avoid having to replace all of the contrasts files across all test profiles. But once the new plugin is released, I'll update the PR with the csv handling removed

2025-01-14 17:28 UTC, nschcolnicov commented
@grst I added the changes you mentioned, pipeline is working and tests are passing. Based on what we discussed [here](https://github.com/nf-core/differentialabundance/issues/370), we now need to merge this [shinyngs PR](https://github.com/pinin4fjords/shinyngs/pull/68), then make a new release, and then upload the nf-core module, so that I can then update this PR with the latest version that allows .yaml contrasts files and I can delete the script in the bin/ folder. Looping @pinin4fjords in.

2025-01-14 18:04 UTC, pinin4fjords commented on workflows/differentialabundance.nf
> +        ch_contrast_variables.dump(tag:"ch_contrasts_variables")
There's no need to remove it from here just now, let's keep backwards compatibility please

2025-01-16 17:10 UTC, pinin4fjords commented
https://github.com/bioconda/bioconda-recipes/pull/53271

2025-01-17 20:20 UTC, nschcolnicov commented
@grst @pinin4fjords All set, please take a look!

2025-01-20 09:34 UTC, grst approved these changes

2025-01-20 11:04 UTC, pinin4fjords requested changes
A couple of comments. Please also update the tube map to reflect the the move away from CSV for contrasts.

Note also that this is quite a breaking change, so the next pipeline release is definitely a major one after this: 2.0.0.

2025-01-20 11:04 UTC, pinin4fjords commented on workflows/differentialabundance.nf
> +        ch_contrast_variables.dump(tag:"ch_contrasts_variables")
Assume this is a test line to be deleted

2025-01-20 11:04 UTC, pinin4fjords commented on workflows/differentialabundance.nf
> +        if (params.contrasts.endsWith(".yaml") || params.contrasts.endsWith(".yml")) {
Is there a need for this conditional if you're fixing things to YML across the board?

2025-01-21 08:59 UTC, grst commented
> Note also that this is quite a breaking change, so the next pipeline release is definitely a major one after this: 2.0.0.

Huh, I thought we kept accepting both formats for now? I'm fine either way, but then we should consider postponing a 2.0 release until we also implemented formula-based model definitions (https://github.com/nf-core/differentialabundance/issues/362) as this might possibly break compatibility to the current yaml format again.

2025-01-21 09:25 UTC, pinin4fjords commented
> Huh, I thought we kept accepting both formats for now? 

I thought so too, but the rest of the changes here seemed to indicate a change of plan.

2025-01-21 11:47 UTC, nschcolnicov commented
@grst I was acting on [this comment](https://github.com/nf-core/differentialabundance/pull/410#discussion_r1908795240). However, I noticed that @pinin4fjords had a different [opinion about it](https://github.com/nf-core/differentialabundance/pull/410#discussion_r1915376134). I can revert the changes regarding CSV compatibility; I just need to know the final decision on this matter.

2025-01-21 11:53 UTC, grst commented
I think the cost of backwards-compatibility is low here, so let's keep it. 
Then we hopefully make breaking changes only once when switching to formula-based model definition.

2025-01-21 14:15 UTC, nschcolnicov commented
@grst  @pinin4fjords Adding backwards compatibility wasn't as trivial as I thought since I couldn't find a way of having a json schema that works for both csv and yaml files. What I did instead was add a line of code that would remove the schema validation from the nextflow_schema.json (and store it into a new schema file), whenever a csv contrasts file is provided. I also added a test case for csv contrasts file so that we don't lose this compatibility with further changes.
https://github.com/nf-core/differentialabundance/pull/410/commits/fa717f159c4aedfe7f4170ffaf9a282d318317ed
Let me know what you think

2025-01-22 11:59 UTC, pinin4fjords commented
> @grst @pinin4fjords Adding backwards compatibility wasn't as trivial as I thought since I couldn't find a way of having a json schema that works for both csv and yaml files. What I did instead was add a line of code that would remove the contrasts schema validation from the nextflow_schema.json (and store it into a new schema file), whenever a csv contrasts file is provided. I also added a test case for csv contrasts file so that we don't lose this compatibility with further changes. [fa717f1](https://github.com/nf-core/differentialabundance/commit/fa717f159c4aedfe7f4170ffaf9a282d318317ed) Let me know what you think

I really don't think we should be dynamically changing workflow files. I see a few options:

1. An extra param (`contrasts_yml` or somesuch), validated separately.
2. (temporarily) no validation at all. 
3. We give up on the backwards compatibility given that there are more overheads than we expected. 

Maybe we just bit the bullet and do 3. I would have liked it to be backwards compatible, but it's not looking very feasible without a high degree of additional complexity.

Thoughts?

2025-01-22 13:22 UTC, nschcolnicov commented
> > @grst @pinin4fjords Adding backwards compatibility wasn't as trivial as I thought since I couldn't find a way of having a json schema that works for both csv and yaml files. What I did instead was add a line of code that would remove the contrasts schema validation from the nextflow_schema.json (and store it into a new schema file), whenever a csv contrasts file is provided. I also added a test case for csv contrasts file so that we don't lose this compatibility with further changes. [fa717f1](https://github.com/nf-core/differentialabundance/commit/fa717f159c4aedfe7f4170ffaf9a282d318317ed) Let me know what you think
> 
> I really don't think we should be dynamically changing workflow files. I see a few options:
> 
> 1. An extra param (`contrasts_yml` or somesuch), validated separately.
> 2. (temporarily) no validation at all.
> 3. We give up on the backwards compatibility given that there are more overheads than we expected.
> 
> Maybe we just bit the bullet and do 3. I would have liked it to be backwards compatible, but it's not looking very feasible without a high degree of additional complexity.
> 
> Thoughts?

I like the idea of keeping backwards compatibility + keeping the validation, so I'm inclined towards the first bullet point. Let me revert the latest commit and add a draft commit with these changes and we can review again.

2025-01-23 12:49 UTC, grst commented
I'm fine with either solution. It will anyway be a temporary solution until we start implementing the formula-based model definition.

2025-01-24 15:00 UTC, nschcolnicov commented
@pinin4fjords What do you think?

2025-01-30 09:13 UTC, grst commented
@pinin4fjords, sorry for bumping this again, but can this be merged?

2025-01-30 10:12 UTC, pinin4fjords approved these changes
Minor change requests, feel free to merge after addressing

2025-01-30 10:12 UTC, pinin4fjords commented on docs/usage.md
> +The contrasts file references the observations file to define groups of samples to compare. It can be provided in both CSV/TSV and YAML format using the parameters `--contrasts` or `--contrasts_yml`,
```suggestion
The contrasts file references the observations file to define groups of samples to compare. It can be provided in **either** CSV/TSV or YAML format using the parameters `--contrasts` or `--contrasts_yml`, respectively. 
```

2025-01-30 10:12 UTC, pinin4fjords commented on docs/usage.md
> +Based on the sample sheet above we could define contrasts like:
```suggestion
The contrasts file references the observations file to define groups of samples to compare. For example, based on the sample sheet above we could define contrasts like:
```

Sorry, I liked that additional bit of doc

2025-01-30 10:18 UTC, grst commented
@nf-core-bot fix linting

2025-01-30 10:30 UTC, merged