Add parameters and random terms for local module `DREAM_DIFFERENTIAL`
nf-core/differentialabundance pull request #416
Opened 2024-12-31 17:19 UTC by alanmmobbs93

## PR checklist

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/differentialabundance/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/differentialabundance _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nf-test test main.nf.test -profile test,docker`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [X] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2025-01-02 22:50 UTC, nschcolnicov commented on modules/local/dream/differential/resources/usr/bin/dream_de.R
>  option_list <- list(
These three options seem to be missing:
stdev.coef.lim
winsor.tail.p
p.value

2025-01-02 22:52 UTC, nschcolnicov requested changes
Please update the docs/usage.md and docs/output.md

2025-01-06 12:53 UTC, alanmmobbs93 commented on modules/local/dream/differential/resources/usr/bin/dream_de.R
>  option_list <- list(
@nschcolnicov Thanks! They are, but with the dots areplaced by underscores. Did you find the parameters as you wrote them somewhere else?

2025-01-06 15:41 UTC, atrigila commented on modules/local/dream/differential/main.nf
>      tuple val(meta), path("*.normalised_counts.tsv")    , emit: normalised_counts, optional: true
Nice to have: the `.yml` file that explains inputs and outputs. This way it can be ready for submission to nf-core modules.

2025-01-06 15:41 UTC, atrigila commented on docs/usage.md
Question: the 'default' pipeline runs all the modes (DREAM, DESeq2, limma)? or one can choose which to run? Perhaps this could be added to the documentation.

2025-01-06 18:10 UTC, alanmmobbs93 commented on docs/usage.md
@atrigila If I got it right, it depends on the "study_type" parameter. `rnaseq` runs DESeq2 by default (or you can force it to use limma with a parameter). The other types run limma

2025-01-07 16:09 UTC, atrigila approved these changes
Makes sense to me from the module's perspective but I am not 100% familiar with the pipeline and method, so we can wait for Nico's feedback as well :)

2025-01-07 16:22 UTC, nschcolnicov commented on modules/local/dream/differential/resources/usr/bin/dream_de.R
>  option_list <- list(
Ahh I see, I saw them written that way in the modules.config:
i.e:
https://github.com/nf-core/differentialabundance/blob/d760b851df2a59868f7b23e012e79c16c58f0540/conf/modules.config#L288

Let me know if I'm making a mistake

2025-01-07 18:30 UTC, nschcolnicov approved these changes
Thanks for addressing the comments!

2025-01-07 19:10 UTC, merged